# List of nCopies of units as they currently are in my account
from dokkanUnitConstants import SLOT_1, SLOT_2, SLOT_3
User = {
    1: {
        "Common Name": "CLR_TEQ_SS_Goku",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    2: {
        "Common Name": "DFLR_PHY_Buu_Bois",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    3: {
        "Common Name": "DFLR_STR_GT_Duo",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 3, 2, 2, 2, 2, 2, 2],
    },
    4: {
        "Common Name": "DFLR_TEQ_Fusion_Zamasu",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    5: {
        "Common Name": "DF_TEQ_Super_Trunks",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 1, 2, 3, 2, 2, 2, 2, 2]
    },
    6: {
        "Common Name": "BU_STR_SS_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    7: {
        "Common Name": "DF_STR_Super_17",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1]
    },
    8: {
        "Common Name": "DF_INT_Majin_Vegeta",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 1, 2, 2, 2, 2],
    },
    9: {
        "Common Name": "DF_STR_Super_Vegeta",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    10: {
        "Common Name": "DF_AGL_Sword_Trunks",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    11: {
        "Common Name": "DF_AGL_Kid_Gohan",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 1, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    12: {
        "Common Name": "CLR_AGL_Omega_Shenron",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    13: {
        "Common Name": "CLR_STR_SS_Goku",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [1, 1, 1, 3, 2, 2, 2, 2, 2, 2],
    },
    14: {
        "Common Name": "LR_AGL_Future_Duo",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    15: {
        "Common Name": "DF_INT_ToP_Androids",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    16: {
        "Common Name": "BU_STR_Universe_2",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    17: {
        "Common Name": "DF_AGL_Berserk_Kale",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 1, 1, 1, 1, 2, 1, 2, 1],
    },
    18: {
        "Common Name": "DF_PHY_God_Goku",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    19: {
        "Common Name": "DF_PHY_Kid_Goku",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 2, 2, 2, 2, 2, 2, 2],
    },
    20: {
        "Common Name": "DF_TEQ_Fusing_Kefla",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 3, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    21: {
        "Common Name": "DF_STR_Costume_Videl",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 3, 3, 3, 3, 3, 1, 1, 1],
    },
    22: {
        "Common Name": "CLR_INT_Kid_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 3, 2, 2, 2, 2, 2, 2, 1],
    },
    23: {
        "Common Name": "CLR_AGL_Kai_Goku",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    24: {
        "Common Name": "LR_TEQ_Universe_2",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 3, 2, 2, 2, 2, 2, 2, 1],
    },
    25: {
        "Common Name": "LR_STR_Bulma_Youth",
        "# Copies": 2,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [3, 3, 3, 2, 2, 2, 2, 2, 1, 1],
    },
    26: {
        "Common Name": "LR_AGL_Caulifla_Kale",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    27: {
        "Common Name": "BU_TEQ_Frost_FinalForm",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    28: {
        "Common Name": "DF_STR_Piccolo_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_2,
    },
    29: {
        "Common Name": "BU_TEQ_Vegeta_Nappa",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_3,
    },
    30: {
        "Common Name": "DF_PHY_Turles_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    31: {
        "Common Name": "DF_TEQ_Bardock_",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    32: {
        "Common Name": "DF_INT_Yamcha_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    33: {
        "Common Name": "DF_AGL_Captain_Ginyu",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 2, 2, 1, 1, 1, 1, 1],
    },
    34: {
        "Common Name": "DF_PHY_Raditz_",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    35: {
        "Common Name": "DF_INT_Hirudegarn_",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    36: {
        "Common Name": "DF_TEQ_WT_Goku",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    37: {
        "Common Name": "DFLR_TEQ_Orange_Piccolo",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    38: {
        "Common Name": "DF_INT_RoF_Blues",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    39: {
        "Common Name": "DF_STR_Goku_Gohan",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    40: {
        "Common Name": "DF_STR_Kid_Buu",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    41: {
        "Common Name": "DF_TEQ_Fat_Janemba",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    42: {
        "Common Name": "DF_STR_SS3_Goku",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [3, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    43: {
        "Common Name": "DF_INT_Piccolo_Jr",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_2,
    },
    44: {
        "Common Name": "DFLR_PHY_Beast_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    45: {
        "Common Name": "DF_TEQ_GT_Pan",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    46: {
        "Common Name": "DF_AGL_Transforming_Cell",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    47: {
        "Common Name": "DF_PHY_SS2_Goku",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    48: {
        "Common Name": "DF_AGL_Paikuhan_",
        "# Copies": 4,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    49: {
        "Common Name": "LR_PHY_Broly_Trio",
        "# Copies": 3,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    50: {
        "Common Name": "LR_STR_UI_Goku",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    51: {
        "Common Name": "CLR_PHY_Metal_Cooler",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    52: {
        "Common Name": "LR_INT_Turles_Goku",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_2,
    },
    53: {
        "Common Name": "CLR_PHY_Future_Trunks",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 2, 2, 2, 2, 2, 2, 2],
    },
    54: {
        "Common Name": "DF_PHY_DBS_Broly",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    55: {
        "Common Name": "DFLR_TEQ_Vegito_Blue",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 1, 3, 3, 3, 3],
    },
    56: {
        "Common Name": "DFLR_STR_Gogeta_Blue",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [3, 1, 3, 1, 3, 3, 3, 3],
    },
    57: {
        "Common Name": "DFLR_PHY_Blue_Boys",
        "# Copies": 3,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    58: {
        "Common Name": "DFLR_TEQ_SS_Gods",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    59: {
        "Common Name": "DFLR_STR_FF_Cooler",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    60: {
        "Common Name": "DF_AGL_Gogeta_Blue",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    61: {
        "Common Name": "DFLR_PHY_SS4_Gogeta",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    62: {
        "Common Name": "DFLR_AGL_SS_Duo",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    63: {
        "Common Name": "DFLR_AGL_Vegito_Blue",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 1, 3, 1, 1, 1, 1, 1, 1],
    },
    64: {
        "Common Name": "CLR_STR_Future_Gohan",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [1, 1, 1, 2, 2, 2, 2, 2, 2, 2],
    },
    65: {
        "Common Name": "BU_INT_Golden_Frieza",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_1,
    },
    66: {
        "Common Name": "DFLR_AGL_DBS_Broly",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 2, 2, 2, 1, 1],
    },
    67: {
        "Common Name": "CLR_PHY_Gogeta_Blue",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    68: {
        "Common Name": "BU_PHY_Gohan_Teen",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 1, 1, 1, 1, 1, 1],
    },
    69: {
        "Common Name": "BU_PHY_Super_Buu",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    70: {
        "Common Name": "BU_AGL_Pan_GT",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 1, 1, 1, 1, 1, 1, 2],
    },
    71: {
        "Common Name": "BU_AGL_General_Rilldo",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    72: {
        "Common Name": "BU_STR_SS_Cabba",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_1,
    },
    73: {
        "Common Name": "BU_STR_Hit_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    74: {
        "Common Name": "BU_TEQ_Tien_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 1, 1, 1, 1, 1, 1],
    },
    75: {
        "Common Name": "BU_TEQ_2ndForm_Cell",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    76: {
        "Common Name": "BU_INT_Kid_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_1,
    },
    77: {
        "Common Name": "BU_INT_Namek_Vegeta",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 1, 1, 1, 1, 1, 1],
    },
    78: {
        "Common Name": "LR_TEQ_SS3_Goku",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 3, 3, 3, 2, 2, 2, 2, 1, 1],
    },
    79: {
        "Common Name": "CLR_INT_SS_Trio",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    80: {
        "Common Name": "LR_PHY_Android_Trio",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 1, 3, 3, 2, 1, 2, 1, 2],
    },
    81: {
        "Common Name": "DFLR_STR_Beast_Gohan",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    82: {
        "Common Name": "BU_AGL_Krillin_Android18",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    83: {
        "Common Name": "CLR_INT_Gammas_",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    84: {
        "Common Name": "DF_PHY_Goku_Black",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 1, 2, 2, 2, 2, 2, 2, 1],
    },
    85: {
        "Common Name": "DFLR_INT_Vegeta_Trunks",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    86: {
        "Common Name": "DF_INT_Future_Gohan",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 1],
    },
    87: {
        "Common Name": "BU_STR_Future_Mai",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 3, 2, 2, 2, 3, 2, 2],
    },
    88: {
        "Common Name": "BU_PHY_Gowasu_Zamasu",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    89: {
        "Common Name": "BU_PHY_Zamasu_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    90: {
        "Common Name": "DFLR_AGL_MUI_Goku",
        "# Copies": 5,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_1,
    },
    91: {
        "Common Name": "DFLR_INT_EvoBlue_Vegeta",
        "# Copies": 5,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_1,
    },
    92: {
        "Common Name": "BU_INT_Vados_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    93: {
        "Common Name": "DF_STR_Transforming_Kelfa",
        "# Copies": 2,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    94: {
        "Common Name": "DFLR_PHY_Buutenks_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    }
}