# List of nCopies of units as they currently are in my account
from dokkanUnitConstants import SLOT_1, SLOT_2, SLOT_3
User = {
    1: {
        "Common Name": "CLR_TEQ_SS_Goku",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    2: {
        "Common Name": "DFLR_PHY_Buu_Bois",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 3, 2, 2, 1, 1, 1, 1, 1],
    },
    3: {
        "Common Name": "DFLR_STR_GT_Duo",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 2, 3, 2, 2, 2, 2, 2, 2],
    },
    4: {
        "Common Name": "DFLR_TEQ_Fusion_Zamasu",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    5: {
        "Common Name": "DF_TEQ_Super_Trunks",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 3, 2, 2, 2, 2, 2]
    },
    6: {
        "Common Name": "BU_STR_SS_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [1, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    7: {
        "Common Name": "DF_STR_Super_17",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 2, 2]
    },
    8: {
        "Common Name": "DF_INT_Majin_Vegeta",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    9: {
        "Common Name": "DF_STR_Super_Vegeta",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    10: {
        "Common Name": "DF_AGL_Sword_Trunks",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    11: {
        "Common Name": "DF_AGL_Kid_Gohan",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    12: {
        "Common Name": "CLR_AGL_Omega_Shenron",
        "# Copies": 2,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    13: {
        "Common Name": "CLR_STR_SS_Goku",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 2, 3, 2, 2, 2, 2, 2],
    },
    14: {
        "Common Name": "LR_AGL_Future_Duo",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    15: {
        "Common Name": "DF_INT_ToP_Androids",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    16: {
        "Common Name": "BU_STR_Universe_2",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 1, 1, 1, 1, 1, 1, 1, 2],
    },
    17: {
        "Common Name": "DF_AGL_Berserk_Kale",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    18: {
        "Common Name": "DF_PHY_God_Goku",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    19: {
        "Common Name": "DF_PHY_Kid_Goku",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    20: {
        "Common Name": "DF_TEQ_Fusing_Kefla",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 1, 1, 1, 1, 1, 1, 1, 2],
    },
    21: {
        "Common Name": "DF_STR_Costume_Videl",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 3, 3, 3, 3, 3, 1, 1, 1],
    },
    22: {
        "Common Name": "CLR_INT_Kid_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    23: {
        "Common Name": "CLR_AGL_Kai_Goku",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
    },
    24: {
        "Common Name": "LR_TEQ_Universe_2",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 3, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    25: {
        "Common Name": "LR_STR_Bulma_Youth",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [3, 3, 3, 2, 2, 2, 2, 1, 1, 1],
    },
    26: {
        "Common Name": "LR_AGL_Caulifla_Kale",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 1, 1, 1, 1, 1, 1],
    },
    27: {
        "Common Name": "BU_TEQ_Frost_FinalForm",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    28: {
        "Common Name": "DF_STR_Piccolo_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 3, 2, 2, 2, 2, 2, 2],
    },
    29: {
        "Common Name": "BU_TEQ_Vegeta_Nappa",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_3,
    },
    30: {
        "Common Name": "DF_PHY_Turles_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    31: {
        "Common Name": "DF_TEQ_Bardock_",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    32: {
        "Common Name": "DF_INT_Yamcha_",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    33: {
        "Common Name": "DF_AGL_Captain_Ginyu",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 1, 1, 1, 1, 1],
    },
    34: {
        "Common Name": "DF_PHY_Raditz_",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    35: {
        "Common Name": "DF_INT_Hirudegarn_",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [3, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    36: {
        "Common Name": "DF_TEQ_WT_Goku",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    37: {
        "Common Name": "DFLR_TEQ_Orange_Piccolo",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [1, 1, 1, 3, 2, 1, 1, 1, 1, 1],
    },
    38: {
        "Common Name": "DF_INT_RoF_Blues",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    39: {
        "Common Name": "DF_STR_Goku_Gohan",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 2, 2, 2, 2, 2],
    },
    40: {
        "Common Name": "DF_STR_Kid_Buu",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    41: {
        "Common Name": "DF_TEQ_Fat_Janemba",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    42: {
        "Common Name": "DF_STR_SS3_Goku",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [3, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    43: {
        "Common Name": "DF_INT_Piccolo_Jr",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    44: {
        "Common Name": "DFLR_PHY_Beast_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 2, 3, 2, 2, 2, 2, 2, 2],
    },
    45: {
        "Common Name": "DF_TEQ_GT_Pan",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    46: {
        "Common Name": "DF_AGL_Transforming_Cell",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 3, 2, 2, 2, 2],
    },
    47: {
        "Common Name": "DF_PHY_SS2_Goku",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    48: {
        "Common Name": "DF_AGL_Paikuhan_",
        "# Copies": 4,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    49: {
        "Common Name": "LR_PHY_Broly_Trio",
        "# Copies": 3,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    50: {
        "Common Name": "LR_STR_UI_Goku",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    51: {
        "Common Name": "CLR_PHY_Metal_Cooler",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    52: {
        "Common Name": "LR_INT_Turles_Goku",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 3, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    53: {
        "Common Name": "CLR_PHY_Future_Trunks",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 2, 1, 3, 2, 2, 2, 2, 2, 2],
    },
    54: {
        "Common Name": "DF_PHY_DBS_Broly",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    55: {
        "Common Name": "DFLR_TEQ_Vegito_Blue",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 1, 3, 3, 3, 3],
    },
    56: {
        "Common Name": "DFLR_STR_Gogeta_Blue",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [3, 1, 3, 1, 3, 3, 3, 3],
    },
    57: {
        "Common Name": "DFLR_PHY_Blue_Boys",
        "# Copies": 3,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    58: {
        "Common Name": "DFLR_TEQ_SS_Gods",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 3, 1, 1, 1, 1, 1, 1, 1, 2],
    },
    59: {
        "Common Name": "DFLR_STR_FF_Cooler",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    60: {
        "Common Name": "DF_AGL_Gogeta_Blue",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    61: {
        "Common Name": "DFLR_PHY_SS4_Gogeta",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    62: {
        "Common Name": "DFLR_AGL_SS_Duo",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    63: {
        "Common Name": "DFLR_AGL_Vegito_Blue",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 1, 3, 1, 1, 1, 1, 1, 1],
    },
    64: {
        "Common Name": "CLR_STR_Future_Gohan",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    65: {
        "Common Name": "BU_INT_Golden_Frieza",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    66: {
        "Common Name": "DFLR_AGL_DBS_Broly",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    67: {
        "Common Name": "CLR_PHY_Gogeta_Blue",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    68: {
        "Common Name": "BU_PHY_Gohan_Teen",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 1, 1, 1, 1, 1, 1],
    },
    69: {
        "Common Name": "BU_PHY_Super_Buu",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    70: {
        "Common Name": "BU_AGL_Pan_GT",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 3, 1, 1, 1, 1, 1, 2],
    },
    71: {
        "Common Name": "BU_AGL_General_Rilldo",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    72: {
        "Common Name": "BU_STR_SS_Cabba",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    73: {
        "Common Name": "BU_STR_Hit_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    74: {
        "Common Name": "BU_TEQ_Tien_",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 1, 1, 1, 1, 1, 1],
    },
    75: {
        "Common Name": "BU_TEQ_2ndForm_Cell",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    76: {
        "Common Name": "BU_INT_Kid_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 3, 1, 1, 1, 1, 1, 1, 1],
    },
    77: {
        "Common Name": "BU_INT_Namek_Vegeta",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 3, 3, 1, 1, 1, 1, 1, 1],
    },
    78: {
        "Common Name": "LR_TEQ_SS3_Goku",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 3, 2, 2, 2, 2, 2, 1],
    },
    79: {
        "Common Name": "CLR_INT_SS_Trio",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    80: {
        "Common Name": "LR_PHY_Android_Trio",
        "# Copies": 2,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 1, 2, 2, 1, 1, 1, 1, 1],
    },
    81: {
        "Common Name": "DFLR_STR_Beast_Gohan",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    82: {
        "Common Name": "BU_AGL_Krillin_Android18",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    83: {
        "Common Name": "CLR_INT_Gammas_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 1, 1, 2, 1, 1, 1, 1, 1],
    },
    84: {
        "Common Name": "DF_PHY_Goku_Black",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 1, 2, 2, 2, 2, 2, 2, 1],
    },
    85: {
        "Common Name": "DFLR_INT_Vegeta_Trunks",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    86: {
        "Common Name": "DF_INT_Future_Gohan",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 2, 2, 2, 2, 2, 2, 2, 1],
    },
    87: {
        "Common Name": "BU_STR_Future_Mai",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 3, 2, 2, 2, 3, 2, 2],
    },
    88: {
        "Common Name": "BU_PHY_Gowasu_Zamasu",
        "# Copies": 2,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    89: {
        "Common Name": "BU_PHY_Zamasu_",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    90: {
        "Common Name": "DFLR_AGL_MUI_Goku",
        "# Copies": 5,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": SLOT_1,
    },
    91: {
        "Common Name": "DFLR_INT_EvoBlue_Vegeta",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [1, 2, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    92: {
        "Common Name": "BU_INT_Vados_",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    93: {
        "Common Name": "DF_STR_Transforming_Kelfa",
        "# Copies": 2,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    94: {
        "Common Name": "DFLR_PHY_Buutenks_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 3, 1, 1, 1, 1, 1],
    },
    95: {
        "Common Name": "DFLR_STR_SS_Vegito",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    96: {
        "Common Name": "BU_INT_Dodoria_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    97: {
        "Common Name": "DF_AGL_1stForm_Frieza",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [1, 2, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    98: {
        "Common Name": "DF_AGL_SS_Bardock",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 1, 1, 1, 1, 2, 2, 2, 2, 2],
    },
    99: {
        "Common Name": "BU_AGL_King_Vegeta",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    100: {
        "Common Name": "DF_TEQ_SS_Vegeta",
        "# Copies": 0,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    101: {
        "Common Name": "DF_AGL_DragonFist_Goku",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    102: {
        "Common Name": "DFLR_INT_SFPS4_Goku",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    103: {
        "Common Name": "DFLR_TEQ_Go_Bros",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    104: {
        "Common Name": "DF_PHY_Piccolo_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    105: {
        "Common Name": "LR_INT_Fusion_Zamasu",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    106: {
        "Common Name": "LR_INT_Goku_Black",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    107: {
        "Common Name": "BU_INT_Android_16",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    108: {
        "Common Name": "BU_AGL_Super_Vegeta",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    109: {
        "Common Name": "BU_TEQ_Katoplesa_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 3, 1, 1, 1, 1, 2],
    },
    110: {
        "Common Name": "DF_PHY_God_Toppo",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 1, 1, 3, 3, 2, 2, 2, 2, 1],
    },
    111: {
        "Common Name": "DFLR_INT_Perfect_Cell",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    112: {
        "Common Name": "LR_INT_God_Goku",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    113: {
        "Common Name": "LR_PHY_Super_Janemba",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    114: {
        "Common Name": "LR_STR_Goku_Hit",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    115: {
        "Common Name": "LR_STR_Beerus_Whis",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 2, 2, 1, 2, 1, 2, 1, 2],
    },
    116: {
        "Common Name": "LR_INT_FP_Boujack",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    117: {
        "Common Name": "LR_TEQ_GreatApe_Vegeta",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [1, 1, 1, 1, 3, 1, 1, 1, 1, 2],
    },
    118: {
        "Common Name": "LR_AGL_Nappa_Vegeta",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 3, 3, 2, 2, 2, 2],
    },
    119: {
        "Common Name": "LR_AGL_Super_Baby",
        "# Copies": 2,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 3, 2, 2, 2, 2, 2],
    },
    120: {
        "Common Name": "LR_AGL_Super_Buu",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    121: {
        "Common Name": "LR_AGL_Golden_Frieza",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    122: {
        "Common Name": "DFLR_AGL_SS2_Gohan",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 2, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    123: {
        "Common Name": "LR_AGL_SBA_Goku",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    124: {
        "Common Name": "BU_PHY_SSR3_CMS",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    125: {
        "Common Name": "BU_PHY_SS4_Vegito",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    126: {
        "Common Name": "DF_PHY_SS_Vegito",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    127: {
        "Common Name": "DF_PHY_Beerus_",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    128: {
        "Common Name": "DF_PHY_Android_17",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    129: {
        "Common Name": "DF_PHY_Transforming_Vegeta",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 2, 2, 3, 2, 2, 2, 2, 2],
    },
    130: {
        "Common Name": "BU_STR_Recoome_Guldo",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    131: {
        "Common Name": "DF_STR_Transforming_Cooler",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    132: {
        "Common Name": "DF_STR_Super_Buu",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    133: {
        "Common Name": "BU_STR_Nappa_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    134: {
        "Common Name": "DF_STR_Gamma_1",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    135: {
        "Common Name": "DF_STR_SSBK_Goku",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [1, 1, 3, 1, 1, 1, 1, 1, 1, 2],
    },
    136: {
        "Common Name": "BU_STR_Kale_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    137: {
        "Common Name": "BU_STR_Piccolo_Cooler",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    138: {
        "Common Name": "BU_STR_WT_Krillin",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    139: {
        "Common Name": "BU_INT_Kid_Pan",
        "# Copies": 4,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    140: {
        "Common Name": "DF_TEQ_Future_Androids",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 3, 3, 2, 2, 2, 2, 2, 2],
    },
    141: {
        "Common Name": "BU_TEQ_Caulifla_",
        "# Copies": 5,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    142: {
        "Common Name": "DF_TEQ_SoH_Trunks",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 2, 2, 1, 1, 1],
    },
    143: {
        "Common Name": "BU_TEQ_God_Goku",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    144: {
        "Common Name": "BU_TEQ_BoG_Vegeta",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 2, 3, 1, 1, 1, 1, 1],
    },
    145: {
        "Common Name": "DF_AGL_Fusion_Zamasu",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    146: {
        "Common Name": "DF_AGL_Android_13",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    147: {
        "Common Name": "BU_AGL_Golden_Frieza",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    148: {
        "Common Name": "BU_AGL_Cell_Jr",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    149: {
        "Common Name": "BU_AGL_SFPS4LB_Vegito",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 2, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    150: {
        "Common Name": "DF_AGL_Gamma_2",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    151: {
        "Common Name": "BU_AGL_Android_8",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    152: {
        "Common Name": "BU_PHY_Giant_Ribrianne",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_2,
    },
    153: {
        "Common Name": "BU_INT_Pride_Troopers",
        "# Copies": 3,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    154: {
        "Common Name": "BU_AGL_SS_Gotenks",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    155: {
        "Common Name": "DF_INT_Transforming_Gotenks",
        "# Copies": 5,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [2, 1, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    156: {
        "Common Name": "DF_TEQ_SS3_Gotenks",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    157: {
        "Common Name": "LR_INT_Ginyu_Force",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    158: {
        "Common Name": "BU_TEQ_Evil_Buu",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    159: {
        "Common Name": "BU_PHY_Gotenks_",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    160: {
        "Common Name": "DF_INT_Fat_Buu",
        "# Copies": 1,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 3, 2, 2, 2, 2, 1, 2],
    },
    161: {
        "Common Name": "DF_AGL_SS3_Goku",
        "# Copies": 1,
        "BRZ Equip": "ATK",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 2, 2, 2, 1, 1],
    },
    162: {
        "Common Name": "DF_AGL_Android_21",
        "# Copies": 0,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "CRT",
        "Slots": [2, 3, 3, 1, 2, 2, 2, 2, 2, 2],
    },
    163: {
        "Common Name": "DF_TEQ_Exchange_Buu",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    },
    164: {
        "Common Name": "DF_TEQ_Ultimate_Gohan",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "CRT",
        "Slots": SLOT_1,
    },
    165: {
        "Common Name": "LR_AGL_Ultimate_Gohan",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "CRT",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 3, 2, 2, 2, 2, 2, 2],
    },
    166: {
        "Common Name": "BU_INT_Hercule_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 1, 1, 1, 1, 1, 1],
    },
    167: {
        "Common Name": "BU_PHY_Buutenks_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    168: {
        "Common Name": "BU_INT_SS_Goten",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    169: {
        "Common Name": "BU_TEQ_Kid_Trunks",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_2,
    },
    170: {
        "Common Name": "DF_PHY_Kid_Buu",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 3, 2, 2, 2, 2, 2, 2, 2],
    },
    171: {
        "Common Name": "DF_STR_SS3_Vegeta",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    172: {
        "Common Name": "BU_INT_Cheelai_",
        "# Copies": 1,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    173: {
        "Common Name": "BU_PHY_Android_21",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [3, 1, 2, 2, 2, 2, 2, 2, 2, 2],
    },
    174: {
        "Common Name": "F2PLR_PHY_Babidi_Buu",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    175: {
        "Common Name": "F2P_PHY_Buyon_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 2, 2, 2, 3, 2, 2, 2, 2],
    },
    176: {
        "Common Name": "F2P_PHY_Gohan_Goku",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    177: {
        "Common Name": "F2PLR_INT_Babidi_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    178: {
        "Common Name": "BU_PHY_Robelu_",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    179: {
        "Common Name": "BU_PHY_Whirus_",
        "# Copies": 5,
        "BRZ Equip": "DGE",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    180: {
        "Common Name": "F2P_PHY_UI_Goku",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    181: {
        "Common Name": "BU_PHY_Kid_Chichi",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    182: {
        "Common Name": "BU_STR_Pan_GT",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    183: {
        "Common Name": "BU_STR_Whis_",
        "# Copies": 3,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_1,
    },
    184: {
        "Common Name": "BU_INT_Masked_King",
        "# Copies": 2,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 3, 1, 1, 1, 1, 1, 1, 1, 1],
    },
    185: {
        "Common Name": "BU_INT_Zamasu_",
        "# Copies": 4,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": [1, 1, 1, 2, 2, 2, 2, 1, 1, 1],
    },
    186: {
        "Common Name": "BU_AGL_SS2_Trunks",
        "# Copies": 0,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "ADD",
        "HiPo Choice # 2": "DGE",
        "Slots": [1, 1, 2, 1, 1, 1, 1, 1, 1, 1],
    },
    187: {
        "Common Name": "F2PLR_TEQ_Trunks_Broly",
        "# Copies": 5,
        "BRZ Equip": "DEF",
        "HiPo Choice # 1": "DGE",
        "HiPo Choice # 2": "ADD",
        "Slots": SLOT_3,
    },
}